version: '3'

services:
  vh-db:
    image: postgres:12.11
    restart: always
    environment:
      - POSTGRES_USER=vh
      - POSTGRES_PASSWORD=123456
    ports:
      - '5433:5432'
    volumes:
      - ./db/init.sh:/docker-entrypoint-initdb.d/10-init.sh
  vh-api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - vh-db
    working_dir: /var/www/api
    container_name: vh-api
    restart: unless-stopped
    tty: true
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SERVER_PORT: 8082
    ports:
      - 8082:8082
    volumes:
      - ./:/var/www/api
    networks:
      - vh-network
networks:
  vh-network:
    driver: bridge

volumes:
  dbdata:
    driver: local