#Config database
spring:
  datasource:
    password: O6PKvRZSyBbRWrzWEag7teV0g9iWd6pe
    url: jdbc:postgresql://john.db.elephantsql.com:5432/uesimvzx?stringtype=unspecified
    username: uesimvzx

  liquibase:
    contexts: run
    enabled: true
    default-schema: vh
    liquibase-schema: public

  profiles:
    default: staging

  security:
    user:
      name: admin
      password: admin

  jpa:
#    hibernate:
#      ddl-auto: update
    show-sql: true
#    open-in-view: false

server:
  port: 8080

cronjob:
  scheduler:
    partitionLearning:
      time: 0 0 7 * * ?
      active: false