#Config database
spring:
  datasource:
    password: 2ee3ddb322263614566ecc20c0cf66126791faf700ed203027a319dee9fb5648
    url: jdbc:postgresql://ec2-3-214-103-146.compute-1.amazonaws.com:5432/d6b26qimpjisgl?stringtype=unspecified
    username: ntelzthdcvtkzi
