#Config database
spring:
  datasource:
    password: O6PKvRZSyBbRWrzWEag7teV0g9iWd6pe
    url: jdbc:postgresql://john.db.elephantsql.com:5432/uesimvzx?stringtype=unspecified
    username: uesimvzx

  liquibase:
    contexts: run
    enabled: true
    default-schema: vh
    liquibase-schema: public