#Config database
spring:
  datasource:
    password: nYSQvdfsj6G0dKRpbLgScDJzqBccfPfe
    url: jdbc:postgresql://john.db.elephantsql.com:5432/uesimvzx?stringtype=unspecified
    username: uesimvzx

  liquibase:
    contexts: run
    enabled: true
    default-schema: vh