#Config database
spring:
  datasource:
    password: O6PKvRZSyBbRWrzWEag7teV0g9iWd6pe
    url: jdbc:postgresql://john.db.elephantsql.com:5432/uesimvzx?stringtype=unspecified
    username: uesimvzx

  profiles:
    active: staging

  liquibase:
    contexts: run
    enabled: true
    default-schema: vh
    liquibase-schema: public

  profiles:
    default: staging

server:
  port: 8080