#Config database
spring:
  datasource:
    password: O6PKvRZSyBbRWrzWEag7teV0g9iWd6pe
    url: jdbc:postgresql://john.db.elephantsql.com:5432/uesimvzx?stringtype=unspecified
    username: uesimvzx

  profiles:
    active: staging

  liquibase:
    contexts: run
    enabled: true
    default-schema: vh
    liquibase-schema: public

  security:
    user:
      name: admin
      password: admin
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/vocahype
          jwk-set-uri: https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-eqwnw%40vocahype.iam.gserviceaccount.com

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      ## Hibernate
      hibernate:
#        dialect: com.vocahype.util.PostgreSQL10JsonDialect
        format_sql: true
#        jdbc:
#          batch_size: 200
#          use_get_generated_keys: true
#        order_inserts: true
#        show_sql: false
#        use_sql_comments: true
#    hibernate:
#      ddl-auto: update
    show-sql: true
#    open-in-view: false

server:
  # If using spring-boot-devtools then hide the trace in exception responses here
  error:
    include-stacktrace: never
  ## Define a custom server port
  port: 8080
  servlet:
    session:
      cookie:
        secure: true

cronjob:
  scheduler:
    partitionLearning:
      time: 0 0 7 * * ?
      active: false

application:
  dictionary-api-url: https://api.dictionaryapi.dev/api/v2/entries/en
  data-word: 1000
  open-ai-api-key: c2stbG5FV2J4NUNKbHpQc1BZdk5LMm9UM0JsYmtGSkM1TnNnd1Z6WEw1TmF1V1lvbDl5