#Config database
spring:
  datasource:
    password: 123456
    url: jdbc:postgresql://localhost:5433/vh?stringtype=unspecified
    username: vh

cronjob:
  scheduler:
    partitionLearning:
      time: 0 0 7 * * ?
      active: true