#Config database
spring:
  datasource:
    password: O6PKvRZSyBbRWrzWEag7teV0g9iWd6pe
    url: jdbc:postgresql://john.db.elephantsql.com:5432/uesimvzx?stringtype=unspecified
    username: uesimvzx

  liquibase:
    contexts: run
    enabled: true
    default-schema: vh
    liquibase-schema: public

  profiles:
    default: staging

  security:
    user:
      name: admin
      password: admin
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/vocahype
          jwk-set-uri: https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-eqwnw%40vocahype.iam.gserviceaccount.com

  jpa:
#    hibernate:
#      ddl-auto: update
    show-sql: true
#    open-in-view: false

server:
  port: 8080

cronjob:
  scheduler:
    partitionLearning:
      time: 0 0 7 * * ?
      active: false

application:
  dictionary-api-url: https://api.dictionaryapi.dev/api/v2/entries/en