#Config database
spring:
  datasource:
    password: c2e0800872c1f271fb740e43e4bb2a6b6f23af7119ff294b7b3f45bfe51049ac
    url: jdbc:postgresql://ec2-34-202-127-5.compute-1.amazonaws.com:5432/dcq1hsdhmbjie5?stringtype=unspecified
    username: cmyecuzxjgvqnp
